blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('comment/create/<int:pk>/',
         views.CreateComment.as_view(), name='add_comment'),
    path('reply/create/<int:pk>/', views.CreateReply.as_view(), name='add_reply'),
    path('archive/tag/<str:name>',
         views.TagPostListView.as_view(), name='tag_post_list')
]

project03/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('markdownx/', include('markdownx.urls'))
]

# 開発環境でのメディアファイルの配信設定
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from markdownx.models import MarkdownxField  # @UnresolvedImport
from django.db.models.fields.related import ForeignKey


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=50, unique=True, null=False)

    def __str__(self):
        return self.name


class PostQuerySet(models.QuerySet):

    def published(self):
        '''公開済みの記事を取得'''
        return self.filter(published_at__lte=timezone.now())


class Post(models.Model):
    title = models.CharField('タイトル', max_length=80)
    author = ForeignKey(settings.AUTH_USER_MODEL,
                        on_delete=models.CASCADE, verbose_name='投稿者')
    tags = models.ManyToManyField(
        Tag, blank=True, verbose_name='タグ')
    description = MarkdownxField(
        '説明文', blank=True, null=True, help_text='一覧ページで表示される投稿の説明文です。')
    content = MarkdownxField('本文', help_text='Markdown形式で記述。')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    published_at = models.DateTimeField('公開日', blank=True, null=True)
    relation_posts = models.ManyToManyField(
        'self', blank=True, verbose_name='関連記事')

    objects = PostQuerySet.as_manager()

    def publish(self):
        self.published_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']


class CommentReplyQueryset(models.QuerySet):

    def approved(self):
        self.filter(is_approve=True)


class Comment(models.Model):
    name = models.CharField('名前', max_length=20)
    text = MarkdownxField('本文', help_text='Markdown形式で記述できます。')
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, verbose_name='対象記事', related_name='comments')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    is_approve = models.BooleanField(default=False)

    objects = CommentReplyQueryset.as_manager()

    def approve(self):
        self.is_approve = True

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.pk})


class Reply(models.Model):
    name = models.CharField('名前', max_length=20)
    text = MarkdownxField('本文', help_text='Markdown形式で記述できます。')
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, verbose_name='対象コメント', related_name='replies')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    is_approve = models.BooleanField(default=False)

    objects = CommentReplyQueryset.as_manager()

    def approve(self):
        self.is_approve = True

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.comment.post.pk})

blog/forms.py
from django import forms
from blog.models import Comment, Reply
from blog.widgets import CustomMarkdownxWidget


class CreateCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'text')
        widgets = {
            'name': forms.widgets.TextInput(
                attrs={'value': '名無し'}
            ),
            'text': CustomMarkdownxWidget(
                attrs={'placeholder': '本文: Markdown形式で記述できます。',
                       'class': 'active'}),
        }

    def __init__(self, *args, **kwargs):
        self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)

    def save(self):
        comment = super().save(commit=False)
        comment.post = self.post
        comment.save()
        return comment


class CreateReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ('name', 'text')
        widgets = {
            'name': forms.widgets.TextInput(
                attrs={'value': '名無し'}
            ),
            'text': CustomMarkdownxWidget(
                attrs={'placeholder': '本文: Markdown形式で記述できます。',
                       'class': 'active'}),
        }

    def __init__(self, *args, **kwargs):
        self.comment = kwargs.pop('comment', None)
        super().__init__(*args, **kwargs)

    def save(self):
        reply = super().save(commit=False)
        reply.comment = self.comment
        reply.save()
        return reply

blog/views.py
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic
from django.db.models import Q, Count
from blog.models import Post, Comment, Reply, Tag
from blog.forms import CreateCommentForm, CreateReplyForm
# Create your views here.


class IndexView(generic.ListView):
    '''
        Post一覧ページ
    '''
    model = Post
    context_object_name = 'posts'
    paginate_by = 10
    base_queryset = None

    def get_queryset(self):
        '''
           Postのqueryset下記の条件により絞り込む。
           ・ アクセスが管理者かどうか
           ・ キーワード検索か
        '''

        if not self.request.user.is_superuser:
            self.base_queryset = self.model.objects.published()
        else:
            self.base_queryset = super().get_queryset()

        queryset = self.base_queryset

        # キーワード検索
        keyword = self.request.GET.get('keyword', None)
        if keyword:
            queryset = queryset.filter(Q(title__icontains=keyword) |
                                       Q(description__icontains=keyword) |
                                       Q(content__icontains=keyword))

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(**kwargs)
        post_pk_list = self.base_queryset.values_list('pk', flat=True)
        ctx['tags'] = Tag.objects.filter(
            post__in=post_pk_list).annotate(Count('post'))
        return ctx


class PostDetailView(generic.DetailView):
    '''
        Post詳細ページ
    '''
    model = Post

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        if (not self.request.user.is_superuser) and (not post.published_at):
            '''
                 >>> 404 'superuserではない場合 かつ 公開されていない投稿の場合'
            '''
            raise Http404()

        return post

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['comment_form'] = CreateCommentForm()
        ctx['reply_form'] = CreateReplyForm()
        ctx['breadcrumb'] = [
            {'name': self.object.title, 'link': None}
        ]
        return ctx


class CreateComment(generic.CreateView):
    '''
        CreateCommentFormのPOST送信後の処理。
    '''
    http_method_names = ['post']  # only request.POST
    model = Comment
    form_class = CreateCommentForm

    def get_form_kwargs(self):
        '''
            Commentに紐づくPostを取得、追加。
        '''
        kwargs = super().get_form_kwargs()
        kwargs['post'] = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        return kwargs

    def form_valid(self, form):
        form.instance.is_approve = self.request.user.is_superuser
        messages.success(self.request, 'コメントを送信しました。管理者が承認することでページに表示されます。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'コメントの投稿に失敗しました。内容を確認してください。')
        return super().form_invalid(form)


class CreateReply(generic.CreateView):
    '''
        ReplyCommentFormのPOST送信後の処理。
    '''
    http_mehod_names = ['post']  # only request.POST
    model = Reply
    form_class = CreateReplyForm

    def get_form_kwargs(self):
        '''
            Replyに紐づくCommentを取得、追加。
        '''
        kwargs = super().get_form_kwargs()
        kwargs['comment'] = get_object_or_404(
            Comment, pk=self.kwargs.get('pk'))
        return kwargs

    def form_valid(self, form):
        form.instance.is_approve = self.request.user.is_superuser
        messages.success(self.request, 'コメントを送信しました。 管理者が承認することでページに表示されます。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'コメントの投稿に失敗しました。内容を確認してください。')
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk': Comment.objects.get(pk=self.kwargs.get('pk')).post.pk})


class TagPostListView(IndexView):
    '''
        タグでの絞り込み検索
        blog.views.IndexViewを継承している。
    '''
    model = Post

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_name = self.kwargs.get('name', None)

        if tag_name:
            queryset = queryset.filter(tags__name=tag_name)
            return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['breadcrumb'] = [
            {'name': self.kwargs.get('name'), 'link': None}
        ]

        return ctx

blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="ja">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{% block title %}ブログ{% endblock %}</title>
	
	<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@3.0.1/github-markdown.min.css"> -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css" integrity="sha256-gsmEoJAws/Kd3CjuOQzLie5Q3yshhvmo7YNtBG7aaEY=" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'blog/css/content.css' %}" />
	<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />	
</head>
<body>
<div class="loader-wrapper">
	<div class="loader">Loading</div>
</div>
<header class="header" >
	<div class="hf-grid-contents container">
		<h1 class="header-title"><a href="{% url 'blog:index' %}">Sample</a></h1>
    </div>
</header>
{% if messages %}
	{% for message in messages %}
	<div class="flash-message {% if message.tags %}is-{{ message.tags }}{% endif %}">
		<div class="container">
			{{ message }}
		</div>
	</div>
	{% endfor %}
{% endif %}


<main class="container">
	{% if breadcrumb %}
	<ol class="breadcrumb">
		<li><a href="/">トップ</a></li>
	{% for element in breadcrumb %}
		{% if element.link %}
		<li>
			<a href="{{ element.link }}">{{ element.name }}</a>
		</li>
		{% else %}
		<li class="active">
			{{ element.name }}
		</li>
		{% endif %}
	{% endfor %}
	</ol>
	{% endif %}
	{% block content %}
	{% endblock %}
</main>

<footer class="footer">
	<div class="hf-grid-contents container">	
	    <p>&copy; 2020 Teppei Hayashi.</p>
	    <ul class="footer-list">
	        <li><a href="https://github.com/TeppeiHayashi/django-blog">Github</a></li>
	    </ul>
    </div>
</footer>
<script src="{% static 'blog/js/app.js' %}"></script>
</body>
</html>

blog/templates/blog/comment_create.html
<div class="modal-mask" id="{{ id }}" data-target="{{ id }}">
	<div class="modal-wrapper">
		<div class="modal-container">
			<button class="icon-button modal-delete" data-target="{{ id }}" type="button"><i class="fa fa-times fa-2x" aria-hidden="true"></i></button>
			<div class="modal-body">	
				<form action="{% url url_reverse pk=target.pk %}" method="POST" class="form" >
					{% csrf_token %}
					{{ form.name }}
					{{ form.text }}
					<input type="submit" value="送信"/>	
				</form>
			</div>
		</div>
	</div>
</div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load blog.app %}

{% block title %}{% title post.title %}{% endblock %}

{% block content %}

	<article>		
		<header id="post-header">
			<h1 class="post-title">{{ post.title }}</h1>
			{% if not post.published_at %}
				<i class="fa fa-lock" aria-hidden="true"></i>
			{% endif %}
			<time>{{ post.created_at|date:"Y年m月j日" }}</time>
			<span class="break">|</span>
			{% for tag in post.tags.all %}
				<span class="tag">{{ tag }}</span>
			{% endfor %}
			
		</header>
		<div id="post" class="main-grid-contents">
			<aside id="side">
				<nav id="toc">
					<p id="tocTitle">目次</p>
				</nav>
			</aside>
			<section id="post-content" class="content">
				{{ post.content | markdown_to_html }}
			</section>
			
			{% if post.relation_posts.all %}
			<section id="relation">
				<h2 class="section-title">関連記事</h2>
				{% for r_post in post.relation_posts.all %}
				<article class="post">			
					<a href="{% url 'blog:post_detail' pk=r_post.pk %}" class="post-link">
						<h2 class="title">
							{% if not r_post.published_at %}
								<i class="fa fa-lock" aria-hidden="true"></i>
							{% endif %}
							{{ r_post.title }}
						</h2>
						<p class="description">{{ r_post.description }}</p>
						{% for tag in r_post.tags.all %} 
						<span class="tag">{{ tag }}</span>
						{% endfor %}
					</a>
				</article>
				{% endfor %}
			</section>
			{% endif %}
			
			<section id="comments">
				<h2 class="section-title">コメント一覧</h2>
				{% for comment in post.comments.all %}
					<div class="comment">
						<p>
							<time>{{ comment.created_at|date:"Y年m月j日" }}</time>
							<span class="break">|</span>
							<span>{{ comment.name }}</span>
							{% if not comment.is_approve %}<i class="fa fa-check-circle" aria-hidden="true" style="color:red;"></i>{% endif %}
						</p>
						<div class="content">
							{{ comment.text | markdown_to_html_with_escape }}
						</div>

						{% for reply in comment.replies.all %}
							<div class="comment is_reply">
								<p>
									<time>{{ reply.created_at|date:"Y年m月j日" }}</time>
									<span class="break">|</span>
									<span>{{ reply.name }}</span>
									{% if not reply.is_approve %}<i class="fa fa-check-circle" aria-hidden="true" style="color:red;"></i>{% endif %}
								</p>
								<div class="content">
									{{ reply.text | markdown_to_html }}
								</div>
							</div>
						{% endfor %}
							<p class="do-reply show-modal" data-target="reply_{{ comment.pk }}">
								返信する
							</p>
						{% include 'blog/comment_create.html' with id="reply_"|addstr:comment.pk form=reply_form target=comment url_reverse='blog:add_reply' %}
					</div>
				{% endfor %}
				<p class="do-comment show-modal" data-target="comment_{{ post.pk }}">新しくコメントする</p>
				
			{% include 'blog/comment_create.html' with id="comment_"|addstr:post.pk form=comment_form target=post url_reverse='blog:add_comment' %}
				
			</section>
			
		</div>
	</article>
	
	
	<!-- highlight.js関連の読み込み -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/vs2015.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
	<script>
		
		   // 記事内の目次要素
			const toc = document.querySelector('#post-content div.toc');
			
			// 目次を複製する
			const copyToc = toc.cloneNode(true);
			
			// 複製した目次を、別の場所に張り付ける。サイドバーに<nav id="toc">がある例
			document.querySelector('nav#toc').appendChild(copyToc);
			
			// 記事内の目次を削除する
			document.querySelector('#post-content').removeChild(toc);
			hljs.initHighlightingOnLoad();
			
			const elements = document.getElementsByClassName('markdownx');

			for (element of elements) {
			    element.addEventListener('markdownx.update', event => {
			        for (const block of document.querySelectorAll('pre code')) {
			            hljs.highlightBlock(block);
			        }
			    });
			}
			
			links = document.querySelectorAll('.content > [id]');
			
			const focus = (e) => {
			    const sy = window.pageYOffset;
			    const borderY = sy + 40;
			    let focusID = null;
			    links.forEach( (el) => {
			        const targetEl = el;
			        const tocEl = document.querySelector(`[href='#${el.id}']`)
			        const y = sy + targetEl.getBoundingClientRect().top ;
			        tocEl.classList.remove("active");
			        if(borderY > y) focusID = el.id;
			    });
			    if(focusID)document.querySelector(`[href='#${focusID}']`).classList.add("active");
			};
			focus();
			window.addEventListener("scroll", focus);
		
		
	</script>
{% endblock  %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load blog.app %}

{% block title %}{% title '一覧' %}{% endblock %}

{% block content %}
<div class="main-grid-contents">

	<aside id="side">
		<section class="side-content">
			<h2 class="side-content-title">キーワード検索</h2>
			<form action="/" method="GET" class="search-form">
				<p class="input-with-icon">
					<i class="fa fa-search" aria-hidden="true"></i>
					<input type="text" name="keyword" value="{{ request.GET.keyword }}"/>
				</p>
			</form>
		</section>
		<section class="side-content">
			<h2 class="side-content-title">タグ検索</h2>
			<p class="all-tags">
				{% for tag in tags %}
					<span><a href="{% url 'blog:tag_post_list' name=tag.name %}">{{ tag }}({{ tag.post__count }})</a></span>
				{% endfor %}
			</p>
		</section>	
	</aside>
	<div>
		<p class="posts-count">{{ paginator.count}}件の検索結果</p>
		{% for post in posts %}
			<article class="post">
				<a href="{% url 'blog:post_detail' pk=post.pk %}" class="post-link">		
					<h2 class="title">
						{% if not post.published_at %}
							<i class="fa fa-lock" aria-hidden="true"></i>
						{% endif %}
						{{ post.title }}
					</h2>
					<p class="description">{{ post.description }}</p>
				
					{% for tag in post.tags.all %} 
					<span class="tag">{{ tag }}</span>
					{% endfor %}
				</a>
			</article>
		{% endfor %}
	</div>
</div>

<nav class="page-list">
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <span class="page current">{{ num }}</span>
        {% else %}
            <a href="?{% url_replace request 'page' num %}" class="page">{{ num }}</a>
        {% endif %}

    {% endfor %}
</nav>


{% endblock %}